#!/bin/bash
#
# Systemd rule generator for ibft interfaces
#
# When booted with 'ip=ibft' dracut will rename the
# interface to 'ibft*'. After systemd has started
# it'll try to rename the interface yet again with
# a persistent name.
# But as the ibft interface is already renamed _and_
# in use, the second renaming will fail and udev
# will complain.
# So add a dummy rule which signals udev the correct name
#
# Interface renaming happes at 80-net-setup-link.rules,
# so we need to hook in before that.
#
IBFT_RULES=/run/udev/rules.d/79-ibft.rules

if [ -d /run/udev/rules.d ] ; then
    rm $IBFT_RULES 2> /dev/null
else
    mkdir -p /run/udev/rules.d
fi

for d in /sys/firmware/ibft/ethernet* ; do
    [ -d "$d" ] || break
    num="${d##*/ethernet}"
    read mac < $d/mac
    printf 'SUBSYSTEM=="net", KERNEL=="ibft*", ACTION=="add", DRIVERS=="?*", ATTR{address}=="%s", ATTR{type}=="1", NAME="ibft%s"\n' "$mac" "$num" >> $IBFT_RULES
done
